### ISSUE TITLE
v0.26.2 needs to include a copy of the web client

### ISSUE THREAD

**Issue by Dikakus** [srd424/audioserve-docker#2]
Hi. First, thank you for your work. It's quite usefull for newbies like me.

I have a problem with the new version v0.26.2 of the docker image. The log says:

> Error: Config/Arguments error: Error in config value client_dir: Directory with web client files "client/dist" does not exists or is not directory

The previous version v.0.24.1 works correctly.

**Comment by srd424** [comment]
Thanks for the feedback - it's good to know someone's actually using it! :) And, yes, known problem, I'm still working on this! Not a great brain/health period at the moment.

The server binary is fine, it just needs pointing at a copy of the new web client which you should be able to steal from somewhere - https://github.com/izderadicka/audioserve-web is the upstream repo, the release tarballs are a little out of date though. If you want the latest you could probably extract them from upstream's x86 docker image. Then bind them into the container (with `-v`, or dump into your existing state directory) and set the `client_dir` config/command line option.

**Comment by Dikakus** [comment]
Ok. I will try to follow your suggestion.

**Comment by srd424** [comment]
As a quick hack I forked the upstream web client repo so I could build the latest web client, I haven't tested this!

https://github.com/srd424/audioserve-web/files/12736036/web-build.zip

**Comment by Dikakus** [comment]
Hi! I've finally extracted the client from the docker x86 docker image and binded the directory when starting the container. It's working now!!! Thank you again.

**Comment by srd424** [comment]
No worries, I'm in the process of trying to fix up the build so this is included automatically. Watch this space :)

**Comment by srd424** [comment]
I need to tidy up the build, but ..

https://github.com/srd424/audioserve-docker/pkgs/container/audioserve-docker/131978887?tag=trunk

.. should be 0.26.2 with the latest web client included. Note that the new web client seems to require HTTPS to be able to login successfully, see https://github.com/izderadicka/audioserve/issues/141.

**Comment by Dikakus** [comment]
I've pulled the last image and the issue is solved. 👍

**Comment by srd424** [comment]
Good to hear! I've streamlined the image build process since then, fixed a couple of bugs. Only user visible change is that there's now a "latest" tag on the image, alongside the specific version number. Let me know if I've managed to break anything :)
