### ISSUE TITLE
No v0.28.6 built

### ISSUE THREAD

**Issue by hugo-akaora** [srd424/audioserve-docker#3]
Hello,
Seems that despite a commit on master, latest version v0.28.6 was not built.
Thank you

**Comment by srd424** [comment]
OK, I'll try to have a look when I can .. a bit snowed under and I have to admit this project has dropped off my radar a bit! It may just be GHA needs kicking ..

**Comment by srd424** [comment]
Oh, it's some dependency issue:

https://github.com/srd424/audioserve-builder/actions/runs/11642681224

```
error: failed to select a version for `env_logger`.
    ... required by package `cachedirtree v0.2.2 (/src.real/crates/cachedirtree)`
versions that meet the requirements `^0.11.3` (locked to 0.11.3) are: 0.11.3

the package `cachedirtree` depends on `env_logger`, with features: `anstream` but `env_logger` does not have these features.
 It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.
```

I'll have a poke about but to say I'm not an expert in the rust ecosystem would be an understatement!

**Comment by srd424** [comment]
OK, rebuilding the builder has pulled in a newer version of rustc etc from ubuntu's -security pocket, by the looks of it, and everything seems to have worked from there. Can you test the new image for me?

**Comment by hugo-akaora** [comment]
All good, thank you, it was quick! :)
